import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/share/Nabvar";
import AuthProvider from "@/contexts/AuthProvider";
import { auth } from "@/libs/authjs/auth";
import LogoutButton from "@/components/share/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <main className="container mx-auto">
            <Navbar session={session} logoutBtn={<LogoutButton />} />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
